### ISSUE TITLE
支持批量导入链接

### ISSUE THREAD

**Issue by shaoyouvip** [lemonfog/lemon-live#11]
我曾经用过多个直播软件，例如和这个一样界面的 simple_live 现在觉得本项目比较适合我的使用习惯，想整理一下都迁移放同一个应用里。能提供一个可以 simple_live 的关注信息导入到本项目的嘛？

毕竟这样导入也就是选择一个应用养老 就只在这里提了。

**Comment by lemonfog** [comment]
在同步输入框粘贴 simple live 导出的文本，然后点击合并即可。simple live 挺好用的，网站不确保可用性，容易被恶意攻击，这几天可疑请求已经消耗了我一个账号的一半免费用量
