### ISSUE TITLE
能否加大图标尺寸

### ISSUE THREAD

**Issue by 2584191127** [lemonfog/lemon-live#2]
现在这个大小有点小了，希望能放大一下，或者给个调节选项
![image](https://github.com/lemonfog/lemon-live/assets/78305714/38fea24d-3ac0-4334-b9b2-1111efc27544)

**Comment by lemonfog** [comment]
后端不存储任何数据。前端如果这样做会消耗更多请求用量和加载时间，排序也是一个很大的问题。

**Comment by lemonfog** [comment]
> 另外分区可以做成像[JustLive](http://live.yj1211.work/index/home/areas)那样吗，就是例如我选择王者荣耀这个分区，那么主播列表里有所以平台的

后端不存储任何数据。前端如果这样做会消耗更多请求用量和加载时间，排序也是一个很大的问题。

**Comment by 2584191127** [comment]
> > 另外分区可以做成像[JustLive](http://live.yj1211.work/index/home/areas)那样吗，就是例如我选择王者荣耀这个分区，那么主播列表里有所以平台的
> 
> 后端不存储任何数据。前端如果这样做会消耗更多请求用量和加载时间，排序也是一个很大的问题。

话说现在的直播间排序还不是按照播放量来的欸，这个能优化一下吗

**Comment by lemonfog** [comment]
一页数量 虎牙120 斗鱼120 哔哩10 抖音15 好像都不能改
人气这东西 不同平台计算不一样 而且根本不靠谱  吸引人罢了
直播间的排序是平台接口返回的，我没有进行排序，在前在后都是平台的处理，有些人气低但是有推荐位，就会在前， 真要排起来效果并不会好到哪去

**Comment by 2584191127** [comment]
> 一页数量 虎牙120 斗鱼120 哔哩10 抖音15 好像都不能改 人气这东西 不同平台计算不一样 而且根本不靠谱 吸引人罢了 直播间的排序是平台接口返回的，我没有进行排序，在前在后都是平台的处理，有些人气低但是有推荐位，就会在前， 真要排起来效果并不会好到哪去

这样啊，那好吧

**Comment by 2584191127** [comment]
大佬，能移植一些[justlive](http://live.yj1211.work/)的功能吗，例如新标签页打开直播间、网页全屏、跳转到官方直播间

**Comment by lemonfog** [comment]
双击新标签页打开 
网页全屏按钮 菜单栏按钮 官方链接  已添加

**Comment by 2584191127** [comment]
> 双击新标签页打开 网页全屏按钮 菜单栏按钮 官方链接 已添加

感谢大佬
