### ISSUE TITLE
能将虎牙的字幕功能添加到lemon-live吗

### ISSUE THREAD

**Issue by 2584191127** [lemonfog/lemon-live#21]
声音开太小听不见主播在说什么，声音开太大有会被主播突然的大叫吵到
有字幕的话就可以把声音调小一点看字幕了

**Comment by lemonfog** [comment]
太难 不会。什么系统啊，你在系统设置里搜一下字幕，应该都有实时字幕功能的，没有自己找软件

**Comment by 2584191127** [comment]
大佬你搞不了就算了，也不是特别需要
