### ISSUE TITLE
直播信息的API接口可以使用吗？

### ISSUE THREAD

**Issue by yzydeveloper** [lemonfog/lemon-live#23]
如何使用 lemon-live 所使用的 api 接口？

**Comment by lemonfog** [comment]
付费



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月7日(周三) 下午2:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lemonfog/lemon-live] 直播信息的API接口可以使用吗？ (Issue #23)




 
如何使用 lemon-live 所使用的 api 接口？

**Comment by yzydeveloper** [comment]
> 付费
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月7日(周三) 下午2:26 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [lemonfog/lemon-live] 直播信息的API接口可以使用吗？ (Issue #23) 如何使用 lemon-live 所使用的 api 接口？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

1851303357这个是你qq吗？我加上了已经，私聊回一下
