### ISSUE TITLE
声音，画面比例，关注，画质

### ISSUE THREAD

**Issue by sjjiqtkgg** [lemonfog/lemon-live#3]
声音：希望能在视频里加上声音开关。
画面比例：同样希望加个，刚开始我说怪怪的。
关注：
![photo_2024-05-11_19-24-25](https://github.com/lemonfog/lemon-live/assets/95971362/ed431b66-2d1a-4036-8e8d-d9e4dfde34c8)
看图。
画质：跟同类比还可以提升

**Comment by sjjiqtkgg** [comment]
是声音开头

**Comment by lemonfog** [comment]
双击进入或退出全屏
如果显示控制条 单击暂停或播放

**Comment by lemonfog** [comment]
> 声音：希望能在视频里加上声音开关。 画面比例：同样希望加个，刚开始我说怪怪的。 关注： ![photo_2024-05-11_19-24-25](https://private-user-images.githubusercontent.com/95971362/329777636-ed431b66-2d1a-4036-8e8d-d9e4dfde34c8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0Mzk4NjEsIm5iZiI6MTcxNTQzOTU2MSwicGF0aCI6Ii85NTk3MTM2Mi8zMjk3Nzc2MzYtZWQ0MzFiNjYtMmQxYS00MDM2LThlOGQtZDllNGRmZGUzNGM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE0NTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZGY4NGYwNjM1NjE5MzgxN2ZhMDY0MjNmMTMxODFlMTk2NDYwMjViZTExZGQ3MTc0M2ZlOGE4NmQ5YjVhMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h0slk7QOXQkKyiyRG467rP9lpdC5ZUX8gAR4Zzcjg3I) 看图。 画质：跟同类比还可以提升

PC端上下键调声音 空格暂停播放 双击进入或退出全屏 如果显示控制条 单击暂停或播放
画面比例 16 : 9  video标签虽然铺满，但是视频显示是居中的 最低宽或高 并没有拉伸或缩小  
关注是好几天前的bug 我放了个修复关注按钮有三天了吧 今天下午刚去掉  你尽快点击修复  
画质获取方式已变更
