### ISSUE TITLE
强烈希望添加音量功能在视频里，增加主页点击刷新，点击关注刷新功能

### ISSUE THREAD

**Issue by sjjiqtkgg** [lemonfog/lemon-live#4]
大佬上次的说键盘调节不是不能用，第一次用的时候还说没有音量调节功能，都是网页静音。强烈建议添加，这样比较直观方便。

点击关注刷新功能，最主要的是关注主播在线跟不在线显示不正确。网页刷新一样

主页点击刷新功能，每次向下拉的时候，再次点击主页没有反应，要拉上或者点击右下顶部，个人建议而且

画质已提高，感谢大佬

**Comment by lemonfog** [comment]
静音是因为浏览器限制自动有声播放。其实点击都有刷新，抖音直播状态查询我给关了，因为抖音限制并发。主页那个只是滚动条没归零，刷新图标定位在顶部所以看不到

**Comment by lemonfog** [comment]
已修复
