### ISSUE TITLE
关于开启右侧弹幕直播卡住不动

### ISSUE THREAD

**Issue by sjjiqtkgg** [lemonfog/lemon-live#5]
在看lol msi开启右侧弹幕过多过快的时候直播会卡住（别的直播不存在问题，可能是弹幕多刷新过快），关闭恢复。在视频开启弹幕没有这种问题。
如果跟电脑配置有关可忽略。

**Comment by lemonfog** [comment]
视频和弹幕没有关系的，而且也不需要多高的配置。不过我看了十几分钟，没有卡过，可能是线路或者网络问题吧。

**Comment by sjjiqtkgg** [comment]
老电脑了，因该跟配置有关
