### ISSUE TITLE
关注列表怎么同步到不同设备上？

### ISSUE THREAD

**Issue by xiongaox** [lemonfog/lemon-live#6]
问题一：我有多个设备，ipad，pc，手机，但是关注列表不能同步，是否能通过webdav这种来同步一下关注列表？切换设备的时候，也方便一些

问题二：有些主播是未开播，但是却显示开播状态的小绿点，希望修复一下，如果未开播的时候，可以显示一个默认封面即可，不用点进去，才发现是未开播

**Comment by lemonfog** [comment]
webdav？天方夜谭。已支持同步，数据保存十分钟。
请把直播状态显示错误的发出来。直播被封禁的不处理。
