### ISSUE TITLE
直播状态显示有问题

### ISSUE THREAD

**Issue by weiqiyue** [lemonfog/lemon-live#7]
开播状态与未开播状态显示有问题，有的未开播但是显示直播中，刷新页面也无济于事😵‍💫😵‍💫

**Comment by lemonfog** [comment]
请把显示错误的直播间信息发出来。

**Comment by weiqiyue** [comment]
> 请把显示错误的直播间信息发出来。

等晚会吧，我看看是不是本地缓存的问题😂
