### ISSUE TITLE
关于这个直播间

### ISSUE THREAD

**Issue by sjjiqtkgg** [lemonfog/lemon-live#9]
![image](https://github.com/lemonfog/lemon-live/assets/95971362/8cf55434-0099-4212-9387-94639618f940)
https://lemonlive.deno.dev/bilibili/play/22792924  这个直播间加载难，时有时没有画面。要多次刷新。还有就是从来没有字幕

**Comment by lemonfog** [comment]
那是直播源的问题，b站和cc我没做弹幕

**Comment by sjjiqtkgg** [comment]
我说呢，搞得我都 是用别的看
